"""Lightweight smoke runner to validate GUI layout and mappings.

This script runs without any GUI toolkit. It creates the framework-neutral
`MainWindow`, optionally loads the UI prototype, creates a fake widget map,
simulates a few interactions, and emits a JSON summary suitable for manual
validation or CI artifact collection.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from harite.gui.views.main_window import MainWindow
from harite.gui.adapters.fake_adapter import create_fake_widget_map


def collect_summary(mainwindow: Any) -> dict:
    bindings = getattr(mainwindow, "_adapter_bindings", None)
    if isinstance(bindings, dict) and "file" in bindings:
        bindings = dict(bindings)
        bindings["file"] = str(bindings["file"])

    return {
        "title": getattr(mainwindow, "title", ""),
        "can_optimize": bool(getattr(mainwindow, "can_optimize", False)),
        "plugin_name": getattr(mainwindow, "plugin_name", ""),
        "available_plugins": list(getattr(mainwindow, "available_plugins", ())),
        "form_state": {
            "input_value": getattr(mainwindow.form_state, "input_value", ""),
            "resolution": getattr(mainwindow.form_state, "resolution", ""),
            "output_dir": getattr(mainwindow.form_state, "output_dir", ""),
        },
        "adapter_bindings": bindings,
    }


def evaluate_summary(summary: dict) -> dict:
    checks = {
        "title_present": bool(summary.get("title")),
        "plugins_available": bool(summary.get("available_plugins")),
        "adapter_bound": bool(summary.get("adapter_bindings")),
        "input_present": bool(summary.get("form_state", {}).get("input_value")),
        "can_optimize": bool(summary.get("can_optimize")),
    }
    failed_checks = [name for name, passed in checks.items() if not passed]
    checks["failed_checks"] = failed_checks
    checks["ok"] = not failed_checks
    return checks


def build_markdown_report(summary: dict, *, scope: str) -> str:
    validation = summary.get("validation", {})

    def as_result(value: bool) -> str:
        return "pass" if value else "fail"

    lines = [
        "### Manual device validation",
        f"- Scope: {scope}",
        f"- title_present: {as_result(bool(validation.get('title_present')))}",
        f"- plugins_available: {as_result(bool(validation.get('plugins_available')))}",
        f"- adapter_bound: {as_result(bool(validation.get('adapter_bound')))}",
        f"- input_present: {as_result(bool(validation.get('input_present')))}",
        f"- can_optimize: {as_result(bool(validation.get('can_optimize')))}",
        f"- GUI smoke: {as_result(bool(validation.get('ok')))}",
        f"- Failed checks: {', '.join(validation.get('failed_checks', [])) or 'none'}",
    ]
    return "\n".join(lines) + "\n"


def build_pr_comment(
    summary: dict,
    *,
    scope: str,
    notes: str,
    optimize_result: str,
    apply_dry_run_result: str,
    apply_do_it_result: str,
) -> str:
    validation = summary.get("validation", {})
    gui_smoke = "pass" if bool(validation.get("ok")) else "fail"
    failed = ", ".join(validation.get("failed_checks", [])) or "none"
    notes_text = notes.strip() or "generated by gui_layout_smoke"

    lines = [
        "### Manual device validation",
        f"- Scope: {scope}",
        f"- optimize: {optimize_result}",
        f"- apply dry-run: {apply_dry_run_result}",
        f"- apply do-it: {apply_do_it_result}",
        f"- GUI smoke: {gui_smoke}",
        f"- Failed checks: {failed}",
        f"- Notes: {notes_text}",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="GUI layout smoke runner")
    parser.add_argument("--simulate", action="store_true", help="simulate a few widget actions")
    parser.add_argument("--validate", action="store_true", help="run built-in validation checks and return non-zero on failure")
    parser.add_argument("--out-file", type=Path, help="write JSON summary to path (default stdout)")
    parser.add_argument("--markdown-out", type=Path, help="write PR-comment-friendly markdown report")
    parser.add_argument("--print-markdown", action="store_true", help="print markdown report to stdout")
    parser.add_argument("--pr-comment-out", type=Path, help="write PR comment template markdown")
    parser.add_argument("--print-pr-comment", action="store_true", help="print PR comment template to stdout")
    parser.add_argument("--scope", default="local/gui-smoke", help="scope text used in markdown report")
    parser.add_argument("--notes", default="", help="notes text used in PR comment template")
    parser.add_argument("--optimize-result", default="n/a (manual)", help="value for optimize line in PR comment")
    parser.add_argument("--apply-dry-run-result", default="n/a (manual)", help="value for apply dry-run line in PR comment")
    parser.add_argument("--apply-do-it-result", default="n/a (if executed)", help="value for apply do-it line in PR comment")
    args = parser.parse_args(argv)

    win = MainWindow()

    # Create a best-effort fake widget map using queued adapter code.
    # We avoid failing the script if UI prototype resource is missing.
    ui_result = None
    try:
        from harite.gui.adapters.ui_loader import load_glade_prototype

        ui_result = load_glade_prototype()
    except Exception:
        ui_result = None

    try:
        if ui_result is not None:
            widgets = create_fake_widget_map(win, ui_result)
        else:
            # Create a minimal map when prototype not available.
            widgets = create_fake_widget_map(win, type("R", (), {"file_path": Path("<none>"), "root_tag": "", "widget_count": 0, "signal_count": 0})())

        if args.simulate:
            if "input_text" in widgets:
                widgets["input_text"]("/tmp/example.jpg")
            if "plugin_change" in widgets and win.available_plugins:
                widgets["plugin_change"](win.available_plugins[0])

    except Exception as exc:
        # Non-fatal: record adapter construction error in summary
        setattr(win, "_adapter_bindings_error", str(exc))

    summary = collect_summary(win)

    if args.validate:
        summary["validation"] = evaluate_summary(summary)

    if args.markdown_out:
        if "validation" not in summary:
            summary["validation"] = evaluate_summary(summary)
        md = build_markdown_report(summary, scope=args.scope)
        args.markdown_out.write_text(md, encoding="utf-8")

    if args.print_markdown:
        if "validation" not in summary:
            summary["validation"] = evaluate_summary(summary)
        print(build_markdown_report(summary, scope=args.scope), end="")

    if args.pr_comment_out:
        if "validation" not in summary:
            summary["validation"] = evaluate_summary(summary)
        pr_md = build_pr_comment(
            summary,
            scope=args.scope,
            notes=args.notes,
            optimize_result=args.optimize_result,
            apply_dry_run_result=args.apply_dry_run_result,
            apply_do_it_result=args.apply_do_it_result,
        )
        args.pr_comment_out.write_text(pr_md, encoding="utf-8")

    if args.print_pr_comment:
        if "validation" not in summary:
            summary["validation"] = evaluate_summary(summary)
        print(
            build_pr_comment(
                summary,
                scope=args.scope,
                notes=args.notes,
                optimize_result=args.optimize_result,
                apply_dry_run_result=args.apply_dry_run_result,
                apply_do_it_result=args.apply_do_it_result,
            ),
            end="",
        )

    out_json = json.dumps(summary, indent=2, ensure_ascii=False)

    if args.out_file:
        args.out_file.write_text(out_json, encoding="utf-8")
    else:
        print(out_json)

    if args.validate and not summary["validation"]["ok"]:
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
