from __future__ import annotations

from typing import Any


SAVE_PATH_DIALOG_OBJECT_ALIASES: tuple[str, ...] = (
    "SavePathDialog",
)

SAVE_PATH_STATE_LABEL_ALIASES: tuple[str, ...] = (
    "lblSavePathState",
)

SETTINGS_DIALOG_OBJECT_ALIASES: tuple[str, ...] = (
    "SettingsDialog",
)


def build_runtime_object_aliases(widgets: dict[str, Any]) -> dict[str, Any]:
    return {
        **_build_main_runtime_object_aliases(widgets),
        **_build_dialog_runtime_object_aliases(widgets),
        **_build_tab_runtime_object_aliases(widgets),
        **_build_footer_runtime_object_aliases(widgets),
    }


def _build_main_runtime_object_aliases(widgets: dict[str, Any]) -> dict[str, Any]:
    return {
        "WallPosit_MainWindow": widgets["window"],
        "main_window": widgets["window"],
        "boxRoot": widgets["root"],
        "lblTopMargin": widgets["top_margin_label"],
        "spnTopMargin": widgets["top_margin_spin"],
        "lblLeftMargin": widgets["left_margin_label"],
        "spnLeftMargin": widgets["left_margin_spin"],
        "lblTitle": widgets["title"],
        "lblSubtitle": widgets["subtitle"],
        "lblMainSection": widgets["main_section_label"],
        "boxMainSection": widgets["main_col"],
        "composeGrid": widgets["compose_grid"],
        "leftDisplayCol": widgets["left_display_grid"],
        "rightDisplayCol": widgets["right_display_grid"],
        "inputRowL": widgets["input_row_l"],
        "inputRowR": widgets["input_row_r"],
        "actionClusterRow": widgets["action_cluster_row"],
        "actionClusterCol": widgets["optimize_group"],
        "tglUpperL": widgets["tgl_upper_l"],
        "tglUpperR": widgets["tgl_upper_r"],
        "tglPushLeftL": widgets["tgl_push_left_l"],
        "tglPushRightL": widgets["tgl_push_right_l"],
        "tglLowerL": widgets["tgl_lower_l"],
        "tglPushLeftR": widgets["tgl_push_left_r"],
        "tglPushRightR": widgets["tgl_push_right_r"],
        "tglLowerR": widgets["tgl_lower_r"],
        "btnGetImgL": widgets["btn_get_img_l"],
        "btnGetImgR": widgets["btn_get_img_r"],
        "lblPickState": widgets["pick_state_label"],
        "entPathL": widgets["input_entry_l"],
        "btnClrPathL": widgets["btn_clr_path_l"],
        "entPathR": widgets["input_entry_r"],
        "btnClrPathR": widgets["btn_clr_path_r"],
        "vbox5": widgets["right_margin_col"],
        "lblRightMargin": widgets["right_margin_label"],
        "spnRightMargin": widgets["right_margin_spin"],
        "hbox12": widgets["bottom_margin_row"],
        "lblBottomMargin": widgets["bottom_margin_label"],
        "spnBottomMargin": widgets["bottom_margin_spin"],
        "lblOptimizeSection": widgets["optimize_section_label"],
        "boxOptimizeSection": widgets["optimize_row"],
        "btnSave": widgets["optimize_btn"],
        "btnOptimize": widgets["optimize_modern_btn"],
        "lblOptimizeResult": widgets["optimize_result"],
        "lblApplySection": widgets["apply_section_label"],
        "boxApplySection": widgets["apply_row"],
        "btnSetWall": widgets["apply_btn"],
        "lblApplyTarget": widgets["apply_target"],
        "lblPreviewSection": widgets["preview_section_label"],
        "boxPreviewSection": widgets["preview_group"],
        "boxPreviewImagesRow": widgets["preview_images_row"],
        "imgPreviewL": widgets["preview_left"],
        "imgPreviewR": widgets["preview_right"],
        "lblPreviewAssignL": widgets["preview_left_assignment"],
        "lblPreviewAssignR": widgets["preview_right_assignment"],
        "lblPreviewResultL": widgets["preview_left_result"],
        "lblPreviewResultR": widgets["preview_right_result"],
        "lblPreviewState": widgets["preview_state_label"],
        "lblPreviewSource": widgets["preview_source_label"],
        "lblPreviewAssist": widgets["preview_assist_label"],
        "radApplySingle": widgets["rad_apply_single"],
        "radApplyPerMonitor": widgets["rad_apply_per_monitor"],
        "lblApplyMode": widgets["apply_mode_label"],
        "lblDoItPlanned": widgets["do_it_plan_label"],
        "lblSaveTarget": widgets["save_target_label"],
        "lblPriorityRule": widgets["priority_note_label"],
        "lblStyleLegend": widgets["style_legend_label"],
        "lblCurrentStateSection": widgets["current_state_section_label"],
        "lblCurrentMargins": widgets["current_margins_label"],
        "lblCurrentStateL": widgets["current_left_label"],
        "lblCurrentStateR": widgets["current_right_label"],
        "lblCommandSection": widgets["command_section_label"],
        "commandTabs": widgets["command_tabs"],
        "hbox14": widgets["command_bar"],
        "btnSetting": widgets["btn_setting"],
        "btnSettings": widgets["btn_setting"],
        "btnSetColor": widgets["btn_set_color"],
        "btnAbout": widgets["btn_about"],
        "btnHelp": widgets["btn_help"],
        "flowRow": widgets["flow_row"],
        "lblFlowLegend": widgets["flow_legend_label"],
    }


def _build_dialog_runtime_object_aliases(widgets: dict[str, Any]) -> dict[str, Any]:
    return {
        "btnSettingsApply": widgets["prefs_apply_btn"],
        "btnSettingsLoad": widgets["prefs_load_btn"],
        "btnSettingsSave": widgets["prefs_save_btn"],
        "btnSettingsClose": widgets["prefs_close_btn"],
        "lblSettingsState": widgets["prefs_state_label"],
        "boxSettingsEditor": widgets["prefs_editor_box"],
        "settingsWindow": widgets["prefs_window"],
        "lblSettingsEditorTitle": widgets["prefs_editor_title"],
        "entSettingsResolution": widgets["prefs_resolution_entry"],
        "entSettingsScaling": widgets["prefs_scaling_entry"],
        "radSettingsTwoScreenAuto": widgets["prefs_two_screen_auto"],
        "radSettingsTwoScreenOn": widgets["prefs_two_screen_on"],
        "radSettingsTwoScreenOff": widgets["prefs_two_screen_off"],
        "entSettingsLDisplay": widgets["prefs_l_display_entry"],
        "entSettingsRDisplay": widgets["prefs_r_display_entry"],
        "entSettingsMargins": widgets["prefs_margins_entry"],
        "entSettingsAlign": widgets["prefs_align_entry"],
        "entSettingsValign": widgets["prefs_valign_entry"],
        "spnSettingsQuality": widgets["prefs_quality_spin"],
        "entSettingsMarginTextMode": widgets["prefs_margin_text_mode_entry"],
        "entSettingsMarginText": widgets["prefs_margin_text_entry"],
        "entSettingsMarginTextPosition": widgets["prefs_margin_text_position_entry"],
        "spnSettingsMarginTextMaxLines": widgets["prefs_margin_text_max_lines_spin"],
        "entSettingsPlugin": widgets["prefs_plugin_entry"],
        "radSettingsApplySingle": widgets["prefs_apply_single"],
        "radSettingsApplyPerMonitor": widgets["prefs_apply_per_monitor"],
        "entSettingsImportPath": widgets["prefs_import_path_entry"],
        "entSettingsExportPath": widgets["prefs_export_path_entry"],
        "ColorDialog": widgets["color_dialog_proxy"],
        "colorWindow": widgets["color_window"],
        "entColorValue": widgets["color_value_entry"],
        "lblColorState": widgets["color_state_label"],
        "btnColorPick": widgets["color_pick_btn"],
        "btnColorApply": widgets["color_apply_btn"],
        "btnColorCancel": widgets["color_cancel_btn"],
        "AboutDialog": widgets["about_dialog_proxy"],
        "aboutWindow": widgets["about_window"],
        "lblAboutTitle": widgets["about_title_label"],
        "lblAboutVersion": widgets["about_version_label"],
        "lblAboutDescription": widgets["about_description_label"],
        "lblAboutCredits": widgets["about_credits_label"],
        "lblAboutLicense": widgets["about_license_label"],
        "btnAboutClose": widgets["about_close_btn"],
        "ImgOpenDialog": widgets["open_dialog_proxy"],
        "SrcdirDialog": widgets["srcdir_dialog_proxy"],
        **{object_name: widgets["settings_dialog_proxy"] for object_name in SETTINGS_DIALOG_OBJECT_ALIASES},
        **{object_name: widgets["save_path_state_label"] for object_name in SAVE_PATH_STATE_LABEL_ALIASES},
        **{object_name: widgets["save_path_dialog_proxy"] for object_name in SAVE_PATH_DIALOG_OBJECT_ALIASES},
    }


def _build_tab_runtime_object_aliases(widgets: dict[str, Any]) -> dict[str, Any]:
    return {
        "watchTab": widgets["watch_tab_box"],
        "marginsTab": widgets["margins_tab_box"],
        "watchControlsRow": widgets["watch_controls_row"],
        "watchDetailRow": widgets["watch_detail_row"],
        "lblMarginsTabTitle": widgets["margins_tab_title"],
        "lblMarginsSection": widgets["margins_section_label"],
        "marginTextTabs": widgets["margin_text_tabs"],
        "marginSettingsPage": widgets["margin_settings_page"],
        "marginTextPage": widgets["margin_text_page"],
        "lblMarginSettingsPreview": widgets["margin_settings_preview_label"],
        "lblMarginTextSection": widgets["margin_text_section_label"],
        "lblMarginTextMode": widgets["margin_text_mode_label"],
        "radMarginTextModeOff": widgets["margin_text_mode_off"],
        "radMarginTextModeSettings": widgets["margin_text_mode_settings"],
        "radMarginTextModeText": widgets["margin_text_mode_text"],
        "radMarginTextModeBoth": widgets["margin_text_mode_both"],
        "txtMarginText": widgets["margin_text_entry"],
        "radMarginTextPositionLeftTop": widgets["margin_position_left_top"],
        "radMarginTextPositionRightBottom": widgets["margin_position_right_bottom"],
        "radMarginTextPositionLeftBottom": widgets["margin_position_left_bottom"],
        "radMarginTextPositionRightTop": widgets["margin_position_right_top"],
        "spnMarginTextMaxLines": widgets["margin_text_max_lines_spin"],
        "btnOpenSrcdirL": widgets["btn_open_srcdir_l"],
        "btnOpenSrcdirR": widgets["btn_open_srcdir_r"],
        "lblWatchSection": widgets["watch_label"],
        "lblWatchTabTitle": widgets["watch_tab_title"],
        "spnInterval": widgets["interval_spin"],
        "lblInterval": widgets["interval_label"],
        "btnDaemonize": widgets["btn_daemonize"],
        "btnCancelDaemonize": widgets["btn_cancel_daemonize"],
        "lblWatchSources": widgets["watch_sources_label"],
        "lblWatchCurrent": widgets["watch_current_label"],
        "lblWatchOutput": widgets["watch_output_label"],
    }


def _build_footer_runtime_object_aliases(widgets: dict[str, Any]) -> dict[str, Any]:
    return {
        "statusbar": widgets["footer_col"],
        "lblStatus": widgets["status_label"],
        "lblError": widgets["error_label"],
        "lblWatchSummary": widgets["watch_summary_label"],
    }